// Autogenerated from Pigeon (v20.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
private class TWKeyChainGeneratedApisPigeonCodecReader: FlutterStandardReader {
}

private class TWKeyChainGeneratedApisPigeonCodecWriter: FlutterStandardWriter {
}

private class TWKeyChainGeneratedApisPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TWKeyChainGeneratedApisPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TWKeyChainGeneratedApisPigeonCodecWriter(data: data)
  }
}

class TWKeyChainGeneratedApisPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TWKeyChainGeneratedApisPigeonCodec(readerWriter: TWKeyChainGeneratedApisPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TwKeyChainHostApi {
  /// Fetches a value from the keychain.
  /// [key] is the key to fetch.
  /// [service] is the service to fetch from.
  /// [accessGroup] is the access group to fetch from.
  /// Returns the value stored in the keychain.
  func fetchKeyChain(key: String, service: String?, accessGroup: String?) throws -> String
  /// Saves a value to the keychain.
  /// [key] is the key to save.
  /// [value] is the value to save.
  /// [service] is the service to save to.
  /// [accessGroup] is the access group to save to.
  func saveKeyChain(key: String, value: String, service: String?, accessGroup: String?) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TwKeyChainHostApiSetup {
  static var codec: FlutterStandardMessageCodec { TWKeyChainGeneratedApisPigeonCodec.shared }
  /// Sets up an instance of `TwKeyChainHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TwKeyChainHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Fetches a value from the keychain.
    /// [key] is the key to fetch.
    /// [service] is the service to fetch from.
    /// [accessGroup] is the access group to fetch from.
    /// Returns the value stored in the keychain.
    let fetchKeyChainChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tw_keychain.TwKeyChainHostApi.fetchKeyChain\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchKeyChainChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let serviceArg: String? = nilOrValue(args[1])
        let accessGroupArg: String? = nilOrValue(args[2])
        do {
          let result = try api.fetchKeyChain(key: keyArg, service: serviceArg, accessGroup: accessGroupArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      fetchKeyChainChannel.setMessageHandler(nil)
    }
    /// Saves a value to the keychain.
    /// [key] is the key to save.
    /// [value] is the value to save.
    /// [service] is the service to save to.
    /// [accessGroup] is the access group to save to.
    let saveKeyChainChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tw_keychain.TwKeyChainHostApi.saveKeyChain\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveKeyChainChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        let serviceArg: String? = nilOrValue(args[2])
        let accessGroupArg: String? = nilOrValue(args[3])
        do {
          try api.saveKeyChain(key: keyArg, value: valueArg, service: serviceArg, accessGroup: accessGroupArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveKeyChainChannel.setMessageHandler(nil)
    }
  }
}
